[package]
name = "chorder"
version = "0.1.0"
edition = "2021"

[dependencies]
enigo = "0.2.0"
rdev = "0.5.3"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
serde_yaml = "0.9.34"
tokio = { version = "1.37.0", features = ["full"] }
tray-item = "0.10.0"
